name: Test
on:
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Download And Unzip
      run: |
          pip3 install requests &
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
          unzip ngrok-v3-stable-darwin-amd64.zip &
          wget -O a.sh https://onedrive.baxx.eu.org/api/raw/?path=/mc/a.sh &
          wget -O b.sh https://onedrive.baxx.eu.org/api/raw/?path=/mc/b.sh 
          chmod +x a.sh b.sh
          ./a.sh

    - name: Start Ngrok
      env:
         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
          chmod +x ngrok
          ./ngrok authtoken "2Ij6rEdAk8MmiSjH1udC0H1IQbZ_21QrMMMP55S4eKNHZV6A7"
          ./ngrok tcp 25565 &
          
    - name: Update DNS
      run: |
          python3 mc.py
    - name: Start Minecraft
      run: |
          ./b.sh
