name: Test
on:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Download And Unzip
      run: |
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          wget -O Bedwars.zip https://onedrive.baxx.eu.org/api/raw/?path=/Minecraft/Bedwars.zip
          unzip ngrok-v3-stable-linux-amd64.zip &
          unzip Bedwars.zip &

    - name: Start Minecraft
      run: |
        screen -S mc -d -m java -Xms512M -Xmx2G -javaagent:slimeworldmanager-classmodifier.jar -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -jar spigot.jar nogui
        
    - name: Start Ngrok
      env:
         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
          chmod +x ngrok
          ./ngrok authtoken "$NGROK_TOKEN"
          ./ngrok tcp 25565 &
          
    - name: SSH connection to Actions
      uses: lem0nb/debugger-action@master
    - name: Sleep
      run: sleep 6h
