name: Test
on:
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Download And Unzip
      run: |
          pip3 install requests &
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
          unzip ngrok-v3-stable-darwin-amd64.zip &
          wget -O Bedwars.zip https://onedrive.baxx.eu.org/api/raw/?path=/mc/Bedwars.zip &
          wget -O survial.zip https://onedrive.baxx.eu.org/api/raw/?path=/mc/survial.zip &
          wget -O Miniwall.zip https://onedrive.baxx.eu.org/api/raw/?path=/mc/Miniwall.zip &
          wget -O skywars.zip https://onedrive.baxx.eu.org/api/raw/?path=/mc/skywars.zip &
          wget -O bridge.zip https://onedrive.baxx.eu.org/api/raw/?path=/mc/bridge.zip &
          wget -O lobby.zip https://onedrive.baxx.eu.org/api/raw/?path=/mc/lobby.zip
          wget -O waterfall.zip https://onedrive.baxx.eu.org/api/raw/?path=/mc/waterfall.zip
          unzip waterfall.zip
          unzip bridge.zip &
          unzip Bedwars.zip &
          unzip lobby.zip &
          unzip survial.zip &
          unzip Miniwall.zip &
          unzip skywars.zip &

    - name: Start Ngrok
      env:
         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
          chmod +x ngrok
          ./ngrok authtoken "$NGROK_TOKEN"
          ./ngrok tcp 25565 &
          
    - name: Update DNS
      run: |
          python3 mc.py
    - name: Start Minecraft
      run: |
        cd lobby
        screen -d -m java -Xms512M -Xmx2G -jar Server.jar nogui
        cd ../
        cd Bedwars
        screen -d -m java -Xms512M -Xmx2G -javaagent:slimeworldmanager-classmodifier.jar -Dfile.encoding=UTF-8 -jar spigot.jar nogui
        cd ../
        cd survial
        screen -d -m java -Xms512M -Xmx2G -jar paper.jar nogui
        cd ../
        cd Miniwall
        screen -d -m java -Xms512M -Xmx2G -jar spigot.jar nogui
        cd ../
        cd skywars
        screen -d -m java -Xms512M -Xmx2G -jar spigot.jar nogui
        cd ../
        cd bridge
        screen -d -m java -Xms512M -Xmx2G -jar paper.jar nogui
        cd ../
        cd waterfall
        java -Xms512M -Xmx2G -Dfile.encoding=UTF-8 -jar waterfall.jar nogui
